### ISSUE TITLE
Method to quick-map the views dictionary 

### ISSUE THREAD

**Issue by simonedamico** [qrush/motion-layout#1]
I mean something like the obj-c macro, you just pass the views variables and infer the key of the dictionary using the variables names

**Comment by qrush** [comment]
Ah, I think you're talking about `NSDictionaryOfVariableBindings`. I couldn't find an equivalent in Ruby for this. Also, I don't think it's that big of a deal to make _one_ hash in Ruby (compared to Objective-C). If you can figure out a way to do this that isn't ugly, I'm all for it.
